// this file holds the data that we operate on.
// it's maybe 3/5 of all the data from AC6 that we'll eventually need.
// the data for the frame parts (heads, cores, arms, legs) is up to date. the rest isn't.

pub fn fill_structs_of_arrays() void {
    fill_arm_unit_normal_soa();
    fill_arm_unit_charge_soa();
    fill_back_unit_missile_launcher_soa();
    fill_head_soa();
    fill_core_soa();
    fill_arms_soa();
    fill_legs_soa();
    fill_legs_tank_soa();
    fill_booster_soa();
    fill_fcs_soa();
    fill_generator_soa();
}

const arm_unit_normal = struct {
    name: []const u8,
    attack_power: u16,
    impact: u16,
    accumulative_impact: u16,
    direct_hit_adjustment: u8,
    recoil: u8,
    ideal_range: u16,
    effective_range: u16,
    rapid_fire: f16,
    magazine_rounds: u8,
    total_rounds: u16,
    reload_time: f16,
    ammunition_cost: u16,
    weight: u16,
    en_load: u16,
    pub fn dps(self: @This()) f32 {
        return @as(f32, @floatFromInt(self.attack_power)) * self.rapid_fire;
    }
    pub fn damage_capacity(self: @This()) u16 {
        return @as(f16, @floatFromInt(self.attack_power * self.magazine_rounds));
    }
    pub fn avg_dps(self: @This()) f32 {
        return @as(f32, @floatFromInt(self.attack_power * self.magazine_rounds)) / ((@as(f32, @floatFromInt(self.magazine_rounds - 1)) / self.rapid_fire) + self.reload_time);
    }
};

pub var arm_unit_normal_soa: struct {
    name: [arm_unit_normal_array.len][]const u8,
    ideal_range: [arm_unit_normal_array.len]u16,
    effective_range: [arm_unit_normal_array.len]u16,
    weight: [arm_unit_normal_array.len]u16,
    en_load: [arm_unit_normal_array.len]u16,
    avg_dps: [arm_unit_normal_array.len]f32,
} = undefined;

fn fill_arm_unit_normal_soa() void {
    for (arm_unit_normal_array, 0..) |e, i| {
        arm_unit_normal_soa.name[i] = e.name;
        arm_unit_normal_soa.ideal_range[i] = e.ideal_range;
        arm_unit_normal_soa.effective_range[i] = e.effective_range;
        arm_unit_normal_soa.weight[i] = e.weight;
        arm_unit_normal_soa.en_load[i] = e.en_load;
        arm_unit_normal_soa.avg_dps[i] = e.avg_dps();
    }
}

const arm_unit_normal_array = [_]arm_unit_normal{
    //causes error: thread 202292 panic: integer overflow
    //arm_unit_normal{
    //    .name = "nothing",
    //    .attack_power = 0,
    //    .impact = 0,
    //    .accumulative_impact = 0,
    //    .direct_hit_adjustment = 0,
    //    .recoil = 0,
    //    .ideal_range = 0,
    //    .effective_range = 0,
    //    .rapid_fire = 0,
    //    .magazine_rounds = 0,
    //    .total_rounds = 0,
    //    .reload_time = 0,
    //    .ammunition_cost = 0,
    //    .weight = 0,
    //    .en_load = 0,
    //},
    arm_unit_normal{
        .name = "RF-024 TURNER",
        .attack_power = 105,
        .impact = 65,
        .accumulative_impact = 28,
        .direct_hit_adjustment = 185,
        .recoil = 13,
        .ideal_range = 171,
        .effective_range = 308,
        .rapid_fire = 3.4,
        .magazine_rounds = 18,
        .total_rounds = 540,
        .reload_time = 2.2,
        .ammunition_cost = 40,
        .weight = 3560,
        .en_load = 102,
    },
    arm_unit_normal{
        .name = "RF-025 SCUDDER",
        .attack_power = 135,
        .impact = 82,
        .accumulative_impact = 39,
        .direct_hit_adjustment = 185,
        .recoil = 15,
        .ideal_range = 173,
        .effective_range = 317,
        .rapid_fire = 2.9,
        .magazine_rounds = 15,
        .total_rounds = 450,
        .reload_time = 2.4,
        .ammunition_cost = 50,
        .weight = 3830,
        .en_load = 153,
    },
    arm_unit_normal{
        .name = "MA-J-201 RANSETSU-AR",
        .attack_power = 77,
        .impact = 64,
        .accumulative_impact = 25,
        .direct_hit_adjustment = 185,
        .recoil = 7,
        .ideal_range = 165,
        .effective_range = 303,
        .rapid_fire = 3.2,
        .magazine_rounds = 18,
        .total_rounds = 450,
        .reload_time = 1.9,
        .ammunition_cost = 40,
        .weight = 3620,
        .en_load = 132,
    },
    arm_unit_normal{
        .name = "MG-014 LUDLOW",
        .attack_power = 42,
        .impact = 41,
        .accumulative_impact = 19,
        .direct_hit_adjustment = 195,
        .recoil = 4,
        .ideal_range = 127,
        .effective_range = 249,
        .rapid_fire = 10.0,
        .magazine_rounds = 30,
        .total_rounds = 720,
        .reload_time = 1.5,
        .ammunition_cost = 20,
        .weight = 2450,
        .en_load = 82,
    },
    arm_unit_normal{
        .name = "DF-MG-02 CHANG-CHEN",
        .attack_power = 39,
        .impact = 40,
        .accumulative_impact = 18,
        .direct_hit_adjustment = 195,
        .recoil = 6,
        .ideal_range = 114,
        .effective_range = 234,
        .rapid_fire = 10.0,
        .magazine_rounds = 45,
        .total_rounds = 990,
        .reload_time = 2.2,
        .ammunition_cost = 20,
        .weight = 3280,
        .en_load = 143,
    },
    arm_unit_normal{
        .name = "WR-0555 ATTACHE",
        .attack_power = 62,
        .impact = 62,
        .accumulative_impact = 25,
        .direct_hit_adjustment = 195,
        .recoil = 7,
        .ideal_range = 143,
        .effective_range = 272,
        .rapid_fire = 5,
        .magazine_rounds = 40,
        .total_rounds = 920,
        .reload_time = 2.1,
        .ammunition_cost = 40,
        .weight = 5110,
        .en_load = 303,
    },
    arm_unit_normal{
        .name = "MA-E-210 ETSUJIN",
        .attack_power = 51,
        .impact = 48,
        .accumulative_impact = 22,
        .direct_hit_adjustment = 193,
        .recoil = 3,
        .ideal_range = 117,
        .effective_range = 236,
        .rapid_fire = 8.1,
        .magazine_rounds = 28,
        .total_rounds = 700,
        .reload_time = 1.5,
        .ammunition_cost = 30,
        .weight = 2810,
        .en_load = 98,
    },
    arm_unit_normal{
        .name = "SG-026 HALDEMAN",
        .attack_power = 576,
        .impact = 360,
        .accumulative_impact = 280,
        .direct_hit_adjustment = 190,
        .recoil = 90,
        .ideal_range = 88,
        .effective_range = 168,
        .rapid_fire = 0.769230769231, //manually calculated
        .magazine_rounds = 1,
        .total_rounds = 66,
        .reload_time = 1.3,
        .ammunition_cost = 200,
        .weight = 3660,
        .en_load = 185,
    },
};

const arm_unit_charge = struct {
    name: []const u8,
    attack_power: u16,
    impact: u16,
    accumulative_impact: u16,
    chg_attack_power: u16,
    chg_impact: u16,
    chg_accum_impact: u16,
    direct_hit_adjustment: u8,
    recoil: u8,
    ideal_range: u16,
    effective_range: u16,
    rapid_fire: f16,
    magazine_rounds: u8,
    total_rounds: u16,
    reload_time: f16,
    ammunition_cost: u16,
    weight: u16,
    en_load: u16,
    pub fn dps(self: @This()) f32 {
        return @as(f32, @floatFromInt(self.attack_power)) * self.rapid_fire;
    }
    pub fn damage_capacity(self: @This()) u16 {
        return @as(u16, @floatFromInt(self.attack_power * self.magazine_rounds));
    }
    pub fn avg_dps(self: @This()) f32 {
        return @as(f32, @floatFromInt(self.attack_power * self.magazine_rounds)) / ((@as(f32, @floatFromInt(self.magazine_rounds - 1)) / self.rapid_fire) + self.reload_time);
    }
};

pub var arm_unit_charge_soa: struct {
    name: [arm_unit_charge_array.len][]const u8,
    ideal_range: [arm_unit_charge_array.len]u16,
    effective_range: [arm_unit_charge_array.len]u16,
    weight: [arm_unit_charge_array.len]u16,
    en_load: [arm_unit_charge_array.len]u16,
    avg_dps: [arm_unit_charge_array.len]f32,
} = undefined;

fn fill_arm_unit_charge_soa() void {
    for (arm_unit_charge_array, 0..) |e, i| {
        arm_unit_charge_soa.name[i] = e.name;
        arm_unit_charge_soa.ideal_range[i] = e.ideal_range;
        arm_unit_charge_soa.effective_range[i] = e.effective_range;
        arm_unit_charge_soa.weight[i] = e.weight;
        arm_unit_charge_soa.en_load[i] = e.en_load;
        arm_unit_charge_soa.avg_dps[i] = e.avg_dps();
    }
}

const arm_unit_charge_array = [_]arm_unit_charge{
    arm_unit_charge{
        .name = "MA-J-200 RANSETSU-RF",
        .attack_power = 224,
        .impact = 245,
        .accumulative_impact = 91,
        .chg_attack_power = 224 * 3,
        .chg_impact = 245 * 3,
        .chg_accum_impact = 91 * 3,
        .direct_hit_adjustment = 220,
        .recoil = 12,
        .ideal_range = 180,
        .effective_range = 321,
        .rapid_fire = 1.5,
        .magazine_rounds = 15,
        .total_rounds = 375,
        .reload_time = 1.8,
        .ammunition_cost = 100,
        .weight = 4210,
        .en_load = 158,
    },
};

pub var back_unit_missile_launcher_soa: struct {
    name: [back_unit_missile_launcher_array.len][]const u8,
    effective_range: [back_unit_missile_launcher_array.len]u16,
    weight: [back_unit_missile_launcher_array.len]u16,
    en_load: [back_unit_missile_launcher_array.len]u16,
    avg_dps: [back_unit_missile_launcher_array.len]f32,
} = undefined;

fn fill_back_unit_missile_launcher_soa() void {
    for (back_unit_missile_launcher_array, 0..) |e, i| {
        back_unit_missile_launcher_soa.name[i] = e.name;
        back_unit_missile_launcher_soa.effective_range[i] = e.effective_range;
        back_unit_missile_launcher_soa.weight[i] = e.weight;
        back_unit_missile_launcher_soa.en_load[i] = e.en_load;
        back_unit_missile_launcher_soa.avg_dps[i] = e.avg_dps();
    }
}

const back_unit_missile_launcher = struct {
    name: []const u8,
    attack_power: u16,
    impact: u16,
    accumulative_impact: u16,
    direct_hit_adjustment: u8,
    guidance: u16,
    effective_range: u16,
    homing_lock_time: f16,
    max_lock_count: u8,
    total_rounds: u16,
    reload_time: f16,
    ammunition_cost: u16,
    weight: u16,
    en_load: u16,
    estimated_firing_time: f16,
    pub fn avg_dps(self: @This()) f32 {
        return @as(f32, @floatFromInt(self.attack_power)) / (self.reload_time + self.homing_lock_time + self.estimated_firing_time);
    }
};

const back_unit_missile_launcher_array = [_]back_unit_missile_launcher{
    .{
        .name = "BML-G1/P20MLT-04",
        .attack_power = 103 * 4,
        .impact = 72 * 4,
        .accumulative_impact = 43 * 4,
        .direct_hit_adjustment = 145,
        .guidance = 180,
        .effective_range = 2500,
        .homing_lock_time = 0.3,
        .max_lock_count = 4,
        .total_rounds = 140,
        .reload_time = 4.0,
        .ammunition_cost = 80,
        .weight = 2120,
        .en_load = 154,
        .estimated_firing_time = 0.25,
    },
    .{
        .name = "BML-G2/P03MLT-06",
        .attack_power = 103 * 6,
        .impact = 72 * 6,
        .accumulative_impact = 43 * 6,
        .direct_hit_adjustment = 145,
        .guidance = 180,
        .effective_range = 2500,
        .homing_lock_time = 0.4,
        .max_lock_count = 6,
        .total_rounds = 228,
        .reload_time = 5.0,
        .ammunition_cost = 80,
        .weight = 3840,
        .en_load = 241,
        .estimated_firing_time = 0.5,
    },
    .{
        .name = "BML-G2/P05MLT-10",
        .attack_power = 103 * 10,
        .impact = 72 * 10,
        .accumulative_impact = 43 * 10,
        .direct_hit_adjustment = 145,
        .guidance = 180,
        .effective_range = 2500,
        .homing_lock_time = 0.8,
        .max_lock_count = 10,
        .total_rounds = 300,
        .reload_time = 6.4,
        .ammunition_cost = 80,
        .weight = 5220,
        .en_load = 320,
        .estimated_firing_time = 1.6,
    },
    .{
        .name = "BML-G2/P19SPL-12",
        .attack_power = 600 * 2,
        .impact = 402 * 2,
        .accumulative_impact = 240 * 2,
        .direct_hit_adjustment = 140,
        .guidance = 145,
        .effective_range = 1425,
        .homing_lock_time = 1.5,
        .max_lock_count = 2,
        .total_rounds = 80,
        .reload_time = 6.0,
        .ammunition_cost = 400,
        .weight = 3580,
        .en_load = 325,
        .estimated_firing_time = 0.5,
    },
    .{
        .name = "BML-G2/P16SPL-08",
        .attack_power = 688,
        .impact = 536,
        .accumulative_impact = 320,
        .direct_hit_adjustment = 140,
        .guidance = 145,
        .effective_range = 1425,
        .homing_lock_time = 1.0,
        .max_lock_count = 1,
        .total_rounds = 40,
        .reload_time = 4.5,
        .ammunition_cost = 500,
        .weight = 2800,
        .en_load = 228,
        .estimated_firing_time = 0, // just a guess. i haven't measured
    },
    .{
        .name = "BML-G2/P17SPL-16",
        .attack_power = 688 * 2,
        .impact = 536 * 2,
        .accumulative_impact = 320 * 2,
        .direct_hit_adjustment = 140,
        .guidance = 145,
        .effective_range = 1425,
        .homing_lock_time = 2.0,
        .max_lock_count = 2,
        .total_rounds = 72,
        .reload_time = 7.7,
        .ammunition_cost = 500,
        .weight = 5010,
        .en_load = 510,
        .estimated_firing_time = 0.5, // just a guess. i haven't measured
    },
    .{
        .name = "BML-G1/P31DUO-02",
        .attack_power = 148 * 4,
        .impact = 94 * 4,
        .accumulative_impact = 62 * 4,
        .direct_hit_adjustment = 150,
        .guidance = 145,
        .effective_range = 500,
        .homing_lock_time = 0.4,
        .max_lock_count = 2,
        .total_rounds = 124,
        .reload_time = 3.5,
        .ammunition_cost = 70,
        .weight = 1900,
        .en_load = 182,
        .estimated_firing_time = 0.15,
    },
    .{
        .name = "BML-G1/P32DUO-03",
        .attack_power = 148 * 6,
        .impact = 94 * 6,
        .accumulative_impact = 62 * 6,
        .direct_hit_adjustment = 150,
        .guidance = 145,
        .effective_range = 500,
        .homing_lock_time = 0.4,
        .max_lock_count = 3,
        .total_rounds = 180,
        .reload_time = 4.3,
        .ammunition_cost = 70,
        .weight = 3450,
        .en_load = 262,
        .estimated_firing_time = 0.23,
    },
    .{
        .name = "BML-G2/P08DUO-03",
        .attack_power = 177 * 6,
        .impact = 111 * 6,
        .accumulative_impact = 72 * 6,
        .direct_hit_adjustment = 150,
        .guidance = 145,
        .effective_range = 500,
        .homing_lock_time = 0.7,
        .max_lock_count = 6,
        .total_rounds = 156,
        .reload_time = 5.8,
        .ammunition_cost = 100,
        .weight = 4020,
        .en_load = 332,
        .estimated_firing_time = 0.7, // just a guess. i haven't measured
    },
};

pub var head_soa: struct {
    name: [head_array.len][]const u8,
    ap: [head_array.len]u16,
    kinetic_defense: [head_array.len]u16,
    energy_defense: [head_array.len]u16,
    explosive_defense: [head_array.len]u16,
    attitude_stability: [head_array.len]u16,
    system_recovery: [head_array.len]u16,
    scan_distance: [head_array.len]u16,
    scan_effect_duration: [head_array.len]f16,
    scan_standby_time: [head_array.len]f16,
    weight: [head_array.len]u16,
    en_load: [head_array.len]u16,
} = undefined;

fn fill_head_soa() void {
    for (head_array, 0..) |e, i| {
        head_soa.name[i] = e.name;
        head_soa.ap[i] = e.ap;
        head_soa.kinetic_defense[i] = e.kinetic_defense;
        head_soa.energy_defense[i] = e.energy_defense;
        head_soa.explosive_defense[i] = e.explosive_defense;
        head_soa.attitude_stability[i] = e.attitude_stability;
        head_soa.system_recovery[i] = e.system_recovery;
        head_soa.scan_distance[i] = e.scan_distance;
        head_soa.scan_effect_duration[i] = e.scan_effect_duration;
        head_soa.scan_standby_time[i] = e.scan_standby_time;
        head_soa.weight[i] = e.weight;
        head_soa.en_load[i] = e.en_load;
    }
}

pub const head = struct {
    name: []const u8,
    ap: u16,
    kinetic_defense: u16,
    energy_defense: u16,
    explosive_defense: u16,
    attitude_stability: u16,
    system_recovery: u16,
    scan_distance: u16,
    scan_effect_duration: f16,
    scan_standby_time: f16,
    weight: u16,
    en_load: u16,
};

pub const head_array = [_]head{
    head{
        .name = "HC-2000 FINDER EYE",
        .ap = 660,
        .kinetic_defense = 157,
        .energy_defense = 142,
        .explosive_defense = 153,
        .attitude_stability = 396,
        .system_recovery = 102,
        .scan_distance = 340,
        .scan_effect_duration = 4.2,
        .scan_standby_time = 3.6,
        .weight = 2670,
        .en_load = 84,
    },
    head{
        .name = "AH-J-124 BASHO",
        .ap = 1250,
        .kinetic_defense = 191,
        .energy_defense = 169,
        .explosive_defense = 192,
        .attitude_stability = 394,
        .system_recovery = 90,
        .scan_distance = 390,
        .scan_effect_duration = 14.4,
        .scan_standby_time = 10.8,
        .weight = 4600,
        .en_load = 95,
    },
    head{
        .name = "AH-J-124/RC JAILBREAK",
        .ap = 1000,
        .kinetic_defense = 181,
        .energy_defense = 159,
        .explosive_defense = 182,
        .attitude_stability = 302,
        .system_recovery = 60,
        .scan_distance = 400,
        .scan_effect_duration = 6,
        .scan_standby_time = 10.8,
        .weight = 4250,
        .en_load = 95,
    },
    head{
        .name = "HD-011 MELANDER",
        .ap = 1010,
        .kinetic_defense = 173,
        .energy_defense = 168,
        .explosive_defense = 170,
        .attitude_stability = 430,
        .system_recovery = 124,
        .scan_distance = 380,
        .scan_effect_duration = 4.8,
        .scan_standby_time = 4.2,
        .weight = 3160,
        .en_load = 135,
    },
    head{
        .name = "HD-033M VERRILL",
        .ap = 1080,
        .kinetic_defense = 188,
        .energy_defense = 185,
        .explosive_defense = 185,
        .attitude_stability = 469,
        .system_recovery = 112,
        .scan_distance = 510,
        .scan_effect_duration = 7.8,
        .scan_standby_time = 5.4,
        .weight = 3830,
        .en_load = 240,
    },
    head{
        .name = "HD-012 MELANDER C3",
        .ap = 1070,
        .kinetic_defense = 175,
        .energy_defense = 177,
        .explosive_defense = 169,
        .attitude_stability = 436,
        .system_recovery = 115,
        .scan_distance = 580,
        .scan_effect_duration = 12.0,
        .scan_standby_time = 10.8,
        .weight = 3300,
        .en_load = 165,
    },
    head{
        .name = "DF-HD-08 TIAN-QIANG",
        .ap = 420,
        .kinetic_defense = 142,
        .energy_defense = 140,
        .explosive_defense = 184,
        .attitude_stability = 267,
        .system_recovery = 79,
        .scan_distance = 300,
        .scan_effect_duration = 7,
        .scan_standby_time = 11.4,
        .weight = 1230,
        .en_load = 88,
    },
    head{
        .name = "VP-44S",
        .ap = 850,
        .kinetic_defense = 170,
        .energy_defense = 172,
        .explosive_defense = 168,
        .attitude_stability = 432,
        .system_recovery = 136,
        .scan_distance = 520,
        .scan_effect_duration = 7.2,
        .scan_standby_time = 5.1,
        .weight = 3080,
        .en_load = 148,
    },
    head{
        .name = "VP-44D",
        .ap = 880,
        .kinetic_defense = 150,
        .energy_defense = 183,
        .explosive_defense = 172,
        .attitude_stability = 496,
        .system_recovery = 100,
        .scan_distance = 530,
        .scan_effect_duration = 14.4,
        .scan_standby_time = 10.2,
        .weight = 3260,
        .en_load = 177,
    },
    head{
        .name = "NACHTREIHER/44E",
        .ap = 590,
        .kinetic_defense = 153,
        .energy_defense = 155,
        .explosive_defense = 152,
        .attitude_stability = 463,
        .system_recovery = 107,
        .scan_distance = 420,
        .scan_effect_duration = 13.2,
        .scan_standby_time = 9.6,
        .weight = 2320,
        .en_load = 210,
    },
    head{
        .name = "KASUAR/44Z",
        .ap = 480,
        .kinetic_defense = 149,
        .energy_defense = 157,
        .explosive_defense = 151,
        .attitude_stability = 498,
        .system_recovery = 128,
        .scan_distance = 620,
        .scan_effect_duration = 5.4,
        .scan_standby_time = 3.6,
        .weight = 2590,
        .en_load = 254,
    },
    head{
        .name = "LAMMERGEIER/44F",
        .ap = 300,
        .kinetic_defense = 130,
        .energy_defense = 153,
        .explosive_defense = 130,
        .attitude_stability = 305,
        .system_recovery = 121,
        .scan_distance = 360,
        .scan_effect_duration = 6.6,
        .scan_standby_time = 8.0,
        .weight = 1050,
        .en_load = 220,
    },
    head{
        .name = "VE-44A",
        .ap = 1060,
        .kinetic_defense = 179,
        .energy_defense = 188,
        .explosive_defense = 178,
        .attitude_stability = 423,
        .system_recovery = 138,
        .scan_distance = 490,
        .scan_effect_duration = 12.6,
        .scan_standby_time = 9.9,
        .weight = 3640,
        .en_load = 182,
    },
    head{
        .name = "VE-44B",
        .ap = 1040,
        .kinetic_defense = 167,
        .energy_defense = 181,
        .explosive_defense = 166,
        .attitude_stability = 450,
        .system_recovery = 154,
        .scan_distance = 700,
        .scan_effect_duration = 18.0,
        .scan_standby_time = 4.8,
        .weight = 4320,
        .en_load = 265,
    },
    .{
        .name = "HC-2000/BC SHADE EYE",
        .ap = 770,
        .kinetic_defense = 174,
        .energy_defense = 167,
        .explosive_defense = 181,
        .attitude_stability = 472,
        .system_recovery = 127,
        .scan_distance = 450,
        .scan_effect_duration = 10.8,
        .scan_standby_time = 9.0,
        .weight = 3090,
        .en_load = 163,
    },

    head{
        .name = "HC-3000 WRECKER",
        .ap = 1130,
        .kinetic_defense = 200,
        .energy_defense = 170,
        .explosive_defense = 187,
        .attitude_stability = 378,
        .system_recovery = 93,
        .scan_distance = 370,
        .scan_effect_duration = 3.0,
        .scan_standby_time = 12.0,
        .weight = 3800,
        .en_load = 102,
    },
    head{
        .name = "HS-5000 APPETIZER",
        .ap = 950,
        .kinetic_defense = 176,
        .energy_defense = 180,
        .explosive_defense = 176,
        .attitude_stability = 418,
        .system_recovery = 98,
        .scan_distance = 610,
        .scan_effect_duration = 6.0,
        .scan_standby_time = 4.8,
        .weight = 3000,
        .en_load = 103,
    },
    head{
        .name = "EL-TH-10 FIRMEZA",
        .ap = 620,
        .kinetic_defense = 156,
        .energy_defense = 158,
        .explosive_defense = 154,
        .attitude_stability = 421,
        .system_recovery = 104,
        .scan_distance = 440,
        .scan_effect_duration = 15.0,
        .scan_standby_time = 9.6,
        .weight = 2370,
        .en_load = 134,
    },
    head{
        .name = "EL-PH-00 ALBA",
        .ap = 600,
        .kinetic_defense = 171,
        .energy_defense = 171,
        .explosive_defense = 171,
        .attitude_stability = 465,
        .system_recovery = 129,
        .scan_distance = 500,
        .scan_effect_duration = 3.6,
        .scan_standby_time = 5.4,
        .weight = 2800,
        .en_load = 205,
    },
    head{
        .name = "20-081 MIND ALPHA",
        .ap = 820,
        .kinetic_defense = 178,
        .energy_defense = 186,
        .explosive_defense = 173,
        .attitude_stability = 462,
        .system_recovery = 109,
        .scan_distance = 430,
        .scan_effect_duration = 6.0,
        .scan_standby_time = 4.8,
        .weight = 3350,
        .en_load = 142,
    },
    head{
        .name = "20-082 MIND BETA",
        .ap = 520,
        .kinetic_defense = 158,
        .energy_defense = 164,
        .explosive_defense = 150,
        .attitude_stability = 536,
        .system_recovery = 96,
        .scan_distance = 540,
        .scan_effect_duration = 12.0,
        .scan_standby_time = 9.0,
        .weight = 3460,
        .en_load = 128,
    },
    head{
        .name = "IA-C01H: EPHEMERA",
        .ap = 990,
        .kinetic_defense = 160,
        .energy_defense = 189,
        .explosive_defense = 186,
        .attitude_stability = 480,
        .system_recovery = 132,
        .scan_distance = 550,
        .scan_effect_duration = 4.8,
        .scan_standby_time = 6.0,
        .weight = 4330,
        .en_load = 233,
    },
    head{
        .name = "IB-CO3H: HAL 826",
        .ap = 930,
        .kinetic_defense = 169,
        .energy_defense = 182,
        .explosive_defense = 180,
        .attitude_stability = 470,
        .system_recovery = 125,
        .scan_distance = 600,
        .scan_effect_duration = 16.8,
        .scan_standby_time = 11.4,
        .weight = 3760,
        .en_load = 215,
    },
};

pub var core_soa: struct {
    name: [core_array.len][]const u8,
    ap: [core_array.len]u16,
    kinetic_defense: [core_array.len]u16,
    energy_defense: [core_array.len]u16,
    explosive_defense: [core_array.len]u16,
    attitude_stability: [core_array.len]u16,
    booster_efficiency_adj: [core_array.len]u8,
    generator_output_adj: [core_array.len]u8,
    generator_supply_adj: [core_array.len]u8,
    weight: [core_array.len]u16,
    en_load: [core_array.len]u16,
} = undefined;

fn fill_core_soa() void {
    for (core_array, 0..) |e, i| {
        core_soa.name[i] = e.name;
        core_soa.ap[i] = e.ap;
        core_soa.kinetic_defense[i] = e.kinetic_defense;
        core_soa.energy_defense[i] = e.energy_defense;
        core_soa.explosive_defense[i] = e.explosive_defense;
        core_soa.attitude_stability[i] = e.attitude_stability;
        core_soa.booster_efficiency_adj[i] = e.booster_efficiency_adj;
        core_soa.generator_output_adj[i] = e.generator_output_adj;
        core_soa.generator_supply_adj[i] = e.generator_supply_adj;
        core_soa.weight[i] = e.weight;
        core_soa.en_load[i] = e.en_load;
    }
}

pub const core = struct {
    name: []const u8,
    ap: u16,
    kinetic_defense: u16,
    energy_defense: u16,
    explosive_defense: u16,
    attitude_stability: u16,
    booster_efficiency_adj: u8,
    generator_output_adj: u8,
    generator_supply_adj: u8,
    weight: u16,
    en_load: u16,
};

pub const core_array = [_]core{
    core{
        .name = "CC-2000 ORBITER",
        .ap = 2780,
        .kinetic_defense = 393,
        .energy_defense = 366,
        .explosive_defense = 374,
        .attitude_stability = 407,
        .booster_efficiency_adj = 100,
        .generator_output_adj = 103,
        .generator_supply_adj = 93,
        .weight = 12650,
        .en_load = 267,
    },
    core{
        .name = "AC-J-120 BASHO",
        .ap = 3840,
        .kinetic_defense = 435,
        .energy_defense = 398,
        .explosive_defense = 460,
        .attitude_stability = 502,
        .booster_efficiency_adj = 119,
        .generator_output_adj = 85,
        .generator_supply_adj = 94,
        .weight = 16100,
        .en_load = 300,
    },
    core{
        .name = "AC-J-120/RC JAILBREAK",
        .ap = 2400,
        .kinetic_defense = 405,
        .energy_defense = 368,
        .explosive_defense = 420,
        .attitude_stability = 403,
        .booster_efficiency_adj = 119,
        .generator_output_adj = 83,
        .generator_supply_adj = 94,
        .weight = 12350,
        .en_load = 300,
    },
    core{
        .name = "BD-011 MELANDER",
        .ap = 3680,
        .kinetic_defense = 438,
        .energy_defense = 380,
        .explosive_defense = 429,
        .attitude_stability = 474,
        .booster_efficiency_adj = 98,
        .generator_output_adj = 105,
        .generator_supply_adj = 97,
        .weight = 15200,
        .en_load = 304,
    },
    core{
        .name = "BD-012 MELANDER C3",
        .ap = 3010,
        .kinetic_defense = 425,
        .energy_defense = 377,
        .explosive_defense = 428,
        .attitude_stability = 433,
        .booster_efficiency_adj = 107,
        .generator_output_adj = 102,
        .generator_supply_adj = 106,
        .weight = 13700,
        .en_load = 322,
    },
    core{
        .name = "DF-BD-08 TIAN-QIANG",
        .ap = 4100,
        .kinetic_defense = 473,
        .energy_defense = 438,
        .explosive_defense = 478,
        .attitude_stability = 629,
        .booster_efficiency_adj = 76,
        .generator_output_adj = 114,
        .generator_supply_adj = 70,
        .weight = 20650,
        .en_load = 388,
    },
    core{
        .name = "VP-40S",
        .ap = 3160,
        .kinetic_defense = 427,
        .energy_defense = 436,
        .explosive_defense = 389,
        .attitude_stability = 446,
        .booster_efficiency_adj = 102,
        .generator_output_adj = 111,
        .generator_supply_adj = 102,
        .weight = 15030,
        .en_load = 337,
    },
    core{
        .name = "NACHTREIHER/40E",
        .ap = 2630,
        .kinetic_defense = 349,
        .energy_defense = 359,
        .explosive_defense = 331,
        .attitude_stability = 366,
        .booster_efficiency_adj = 126,
        .generator_output_adj = 91,
        .generator_supply_adj = 109,
        .weight = 9820,
        .en_load = 330,
    },
    core{
        .name = "LAMMERGEIER/40F",
        .ap = 2470,
        .kinetic_defense = 330,
        .energy_defense = 390,
        .explosive_defense = 337,
        .attitude_stability = 354,
        .booster_efficiency_adj = 87,
        .generator_output_adj = 117,
        .generator_supply_adj = 110,
        .weight = 9700,
        .en_load = 341,
    },
    core{
        .name = "VE-40A",
        .ap = 4320,
        .kinetic_defense = 447,
        .energy_defense = 495,
        .explosive_defense = 458,
        .attitude_stability = 521,
        .booster_efficiency_adj = 81,
        .generator_output_adj = 122,
        .generator_supply_adj = 95,
        .weight = 21100,
        .en_load = 432,
    },
    core{
        .name = "CC-3000 WRECKER",
        .ap = 3940,
        .kinetic_defense = 468,
        .energy_defense = 434,
        .explosive_defense = 461,
        .attitude_stability = 532,
        .booster_efficiency_adj = 80,
        .generator_output_adj = 96,
        .generator_supply_adj = 100,
        .weight = 19000,
        .en_load = 310,
    },
    core{
        .name = "CS-5000 MAIN DISH",
        .ap = 3890,
        .kinetic_defense = 476,
        .energy_defense = 489,
        .explosive_defense = 469,
        .attitude_stability = 641,
        .booster_efficiency_adj = 79,
        .generator_output_adj = 97,
        .generator_supply_adj = 112,
        .weight = 23600,
        .en_load = 413,
    },
    core{
        .name = "EL-TC-10 FIRMEZA",
        .ap = 2650,
        .kinetic_defense = 384,
        .energy_defense = 360,
        .explosive_defense = 375,
        .attitude_stability = 410,
        .booster_efficiency_adj = 111,
        .generator_output_adj = 109,
        .generator_supply_adj = 89,
        .weight = 10890,
        .en_load = 351,
    },
    core{
        .name = "EL-PC-00 ALBA",
        .ap = 2850,
        .kinetic_defense = 370,
        .energy_defense = 370,
        .explosive_defense = 370,
        .attitude_stability = 368,
        .booster_efficiency_adj = 115,
        .generator_output_adj = 101,
        .generator_supply_adj = 105,
        .weight = 12000,
        .en_load = 315,
    },
    core{
        .name = "07-061 MIND ALPHA",
        .ap = 3520,
        .kinetic_defense = 440,
        .energy_defense = 455,
        .explosive_defense = 445,
        .attitude_stability = 455,
        .booster_efficiency_adj = 95,
        .generator_output_adj = 112,
        .generator_supply_adj = 104,
        .weight = 16510,
        .en_load = 364,
    },
    core{
        .name = "IA-C01C: EPHEMERA",
        .ap = 2710,
        .kinetic_defense = 335,
        .energy_defense = 382,
        .explosive_defense = 350,
        .attitude_stability = 353,
        .booster_efficiency_adj = 101,
        .generator_output_adj = 126,
        .generator_supply_adj = 96,
        .weight = 13200,
        .en_load = 412,
    },
    core{
        .name = "IB-C03C: HAL 826",
        .ap = 3670,
        .kinetic_defense = 451,
        .energy_defense = 469,
        .explosive_defense = 463,
        .attitude_stability = 385,
        .booster_efficiency_adj = 96,
        .generator_output_adj = 120,
        .generator_supply_adj = 108,
        .weight = 18520,
        .en_load = 366,
    },
};

pub var arms_soa: struct {
    name: [arms_array.len][]const u8,
    ap: [arms_array.len]u16,
    kinetic_defense: [arms_array.len]u16,
    energy_defense: [arms_array.len]u16,
    explosive_defense: [arms_array.len]u16,
    arms_load_limit: [arms_array.len]u16,
    recoil_control: [arms_array.len]u8,
    firearm_specialization: [arms_array.len]u8,
    melee_specialization: [arms_array.len]u8,
    weight: [arms_array.len]u16,
    en_load: [arms_array.len]u16,
} = undefined;

fn fill_arms_soa() void {
    for (arms_array, 0..) |e, i| {
        arms_soa.name[i] = e.name;
        arms_soa.ap[i] = e.ap;
        arms_soa.kinetic_defense[i] = e.kinetic_defense;
        arms_soa.energy_defense[i] = e.energy_defense;
        arms_soa.explosive_defense[i] = e.explosive_defense;
        arms_soa.arms_load_limit[i] = e.arms_load_limit;
        arms_soa.recoil_control[i] = e.recoil_control;
        arms_soa.firearm_specialization[i] = e.firearm_specialization;
        arms_soa.melee_specialization[i] = e.melee_specialization;
        arms_soa.weight[i] = e.weight;
        arms_soa.en_load[i] = e.en_load;
    }
}

pub const arms = struct {
    name: []const u8,
    ap: u16,
    kinetic_defense: u16,
    energy_defense: u16,
    explosive_defense: u16,
    arms_load_limit: u16,
    recoil_control: u8,
    firearm_specialization: u8,
    melee_specialization: u8,
    weight: u16,
    en_load: u16,
};

pub const arms_array = [_]arms{
    arms{
        .name = "AC-2000 TOOL ARM",
        .ap = 1990,
        .kinetic_defense = 207,
        .energy_defense = 204,
        .explosive_defense = 209,
        .arms_load_limit = 13300,
        .recoil_control = 110,
        .firearm_specialization = 96,
        .melee_specialization = 100,
        .weight = 11300,
        .en_load = 216,
    },
    arms{
        .name = "AA-J-123 BASHO",
        .ap = 2430,
        .kinetic_defense = 208,
        .energy_defense = 191,
        .explosive_defense = 225,
        .arms_load_limit = 10520,
        .recoil_control = 66,
        .firearm_specialization = 53,
        .melee_specialization = 158,
        .weight = 10480,
        .en_load = 210,
    },
    arms{
        .name = "AA-J-123/RC JAILBREAK",
        .ap = 1000,
        .kinetic_defense = 180,
        .energy_defense = 190,
        .explosive_defense = 215,
        .arms_load_limit = 10520,
        .recoil_control = 45,
        .firearm_specialization = 45,
        .melee_specialization = 112,
        .weight = 8480,
        .en_load = 210,
    },
    arms{
        .name = "AR-011 MELANDER",
        .ap = 2260,
        .kinetic_defense = 247,
        .energy_defense = 217,
        .explosive_defense = 234,
        .arms_load_limit = 15100,
        .recoil_control = 128,
        .firearm_specialization = 100,
        .melee_specialization = 124,
        .weight = 13650,
        .en_load = 265,
    },
    arms{
        .name = "AR-012 MELANDER C3",
        .ap = 2010,
        .kinetic_defense = 239,
        .energy_defense = 212,
        .explosive_defense = 233,
        .arms_load_limit = 12000,
        .recoil_control = 102,
        .firearm_specialization = 135,
        .melee_specialization = 110,
        .weight = 12000,
        .en_load = 232,
    },
    arms{
        .name = "DF-AR-08 TIAN-QIANG",
        .ap = 2480,
        .kinetic_defense = 260,
        .energy_defense = 250,
        .explosive_defense = 251,
        .arms_load_limit = 19500,
        .recoil_control = 155,
        .firearm_specialization = 92,
        .melee_specialization = 94,
        .weight = 20020,
        .en_load = 295,
    },
    arms{
        .name = "DF-AR-09 TIAN-LAO",
        .ap = 2970,
        .kinetic_defense = 305,
        .energy_defense = 251,
        .explosive_defense = 277,
        .arms_load_limit = 17200,
        .recoil_control = 145,
        .firearm_specialization = 76,
        .melee_specialization = 81,
        .weight = 26740,
        .en_load = 266,
    },
    arms{
        .name = "VP-46S",
        .ap = 2240,
        .kinetic_defense = 231,
        .energy_defense = 252,
        .explosive_defense = 218,
        .arms_load_limit = 14520,
        .recoil_control = 116,
        .firearm_specialization = 102,
        .melee_specialization = 138,
        .weight = 14020,
        .en_load = 278,
    },
    arms{
        .name = "VP-46D",
        .ap = 1620,
        .kinetic_defense = 196,
        .energy_defense = 230,
        .explosive_defense = 190,
        .arms_load_limit = 11800,
        .recoil_control = 105,
        .firearm_specialization = 133,
        .melee_specialization = 139,
        .weight = 10990,
        .en_load = 248,
    },
    arms{
        .name = "NACHTREIHER/46E",
        .ap = 1860,
        .kinetic_defense = 204,
        .energy_defense = 213,
        .explosive_defense = 195,
        .arms_load_limit = 12730,
        .recoil_control = 87,
        .firearm_specialization = 160,
        .melee_specialization = 95,
        .weight = 11420,
        .en_load = 290,
    },
    arms{
        .name = "LAMMERGEIER/46F",
        .ap = 1590,
        .kinetic_defense = 189,
        .energy_defense = 246,
        .explosive_defense = 180,
        .arms_load_limit = 11970,
        .recoil_control = 134,
        .firearm_specialization = 87,
        .melee_specialization = 115,
        .weight = 9700,
        .en_load = 328,
    },
    arms{
        .name = "VE-46A",
        .ap = 2660,
        .kinetic_defense = 262,
        .energy_defense = 270,
        .explosive_defense = 257,
        .arms_load_limit = 21300,
        .recoil_control = 170,
        .firearm_specialization = 80,
        .melee_specialization = 98,
        .weight = 22210,
        .en_load = 380,
    },
    arms{
        .name = "AC-3000 WRECKER",
        .ap = 2030,
        .kinetic_defense = 232,
        .energy_defense = 170,
        .explosive_defense = 237,
        .arms_load_limit = 15800,
        .recoil_control = 232,
        .firearm_specialization = 26,
        .melee_specialization = 72,
        .weight = 14150,
        .en_load = 220,
    },
    arms{
        .name = "AS-5000 SALAD",
        .ap = 2600,
        .kinetic_defense = 258,
        .energy_defense = 271,
        .explosive_defense = 255,
        .arms_load_limit = 18700,
        .recoil_control = 140,
        .firearm_specialization = 88,
        .melee_specialization = 131,
        .weight = 20940,
        .en_load = 218,
    },
    arms{
        .name = "EL-TA-10 FIRMEZA",
        .ap = 1900,
        .kinetic_defense = 210,
        .energy_defense = 214,
        .explosive_defense = 187,
        .arms_load_limit = 13540,
        .recoil_control = 111,
        .firearm_specialization = 122,
        .melee_specialization = 120,
        .weight = 11220,
        .en_load = 270,
    },
    arms{
        .name = "EL-PA-00 ALBA",
        .ap = 1750,
        .kinetic_defense = 205,
        .energy_defense = 205,
        .explosive_defense = 205,
        .arms_load_limit = 11350,
        .recoil_control = 101,
        .firearm_specialization = 140,
        .melee_specialization = 91,
        .weight = 9810,
        .en_load = 315,
    },
    arms{
        .name = "04-101 MIND ALPHA",
        .ap = 2300,
        .kinetic_defense = 245,
        .energy_defense = 260,
        .explosive_defense = 246,
        .arms_load_limit = 15550,
        .recoil_control = 142,
        .firearm_specialization = 103,
        .melee_specialization = 88,
        .weight = 16960,
        .en_load = 358,
    },
    arms{
        .name = "IA-C01A: EPHEMERA",
        .ap = 2380,
        .kinetic_defense = 219,
        .energy_defense = 263,
        .explosive_defense = 256,
        .arms_load_limit = 12680,
        .recoil_control = 108,
        .firearm_specialization = 104,
        .melee_specialization = 106,
        .weight = 12700,
        .en_load = 312,
    },
    arms{
        .name = "IB-C03A: HAL 826",
        .ap = 2210,
        .kinetic_defense = 225,
        .energy_defense = 248,
        .explosive_defense = 236,
        .arms_load_limit = 14000,
        .recoil_control = 125,
        .firearm_specialization = 123,
        .melee_specialization = 114,
        .weight = 14160,
        .en_load = 300,
    },
};

pub var legs_soa: struct {
    name: [legs_array.len][]const u8,
    type: [legs_array.len]legs_type,
    ap: [legs_array.len]u16,
    kinetic_defense: [legs_array.len]u16,
    energy_defense: [legs_array.len]u16,
    explosive_defense: [legs_array.len]u16,
    attitude_stability: [legs_array.len]u16,
    load_limit: [legs_array.len]u32,
    jump_distance: [legs_array.len]u16,
    jump_height: [legs_array.len]u8,
    weight: [legs_array.len]u16,
    en_load: [legs_array.len]u16,
} = undefined;

fn fill_legs_soa() void {
    for (legs_array, 0..) |e, i| {
        legs_soa.name[i] = e.name;
        legs_soa.type[i] = e.type;
        legs_soa.ap[i] = e.ap;
        legs_soa.kinetic_defense[i] = e.kinetic_defense;
        legs_soa.energy_defense[i] = e.energy_defense;
        legs_soa.explosive_defense[i] = e.explosive_defense;
        legs_soa.attitude_stability[i] = e.attitude_stability;
        legs_soa.load_limit[i] = e.load_limit;
        legs_soa.jump_distance[i] = e.jump_distance;
        legs_soa.jump_height[i] = e.jump_height;
        legs_soa.weight[i] = e.weight;
        legs_soa.en_load[i] = e.en_load;
    }
}

const legs_type = enum { bipedal, reverse_joint, tetrapod, tank };

pub const legs = struct {
    name: []const u8,
    type: legs_type,
    ap: u16,
    kinetic_defense: u16,
    energy_defense: u16,
    explosive_defense: u16,
    attitude_stability: u16,
    load_limit: u32,
    jump_distance: u16,
    jump_height: u8,
    weight: u16,
    en_load: u16,
};

pub const legs_array = [_]legs{
    legs{
        .name = "2C-2000 CRAWLER",
        .type = legs_type.bipedal,
        .ap = 3650,
        .kinetic_defense = 326,
        .energy_defense = 322,
        .explosive_defense = 337,
        .attitude_stability = 799,
        .load_limit = 53700,
        .jump_distance = 100,
        .jump_height = 27,
        .weight = 16300,
        .en_load = 280,
    },
    legs{
        .name = "AL-J-121 BASHO",
        .type = legs_type.bipedal,
        .ap = 4240,
        .kinetic_defense = 362,
        .energy_defense = 325,
        .explosive_defense = 398,
        .attitude_stability = 824,
        .load_limit = 62600,
        .jump_distance = 152,
        .jump_height = 29,
        .weight = 19720,
        .en_load = 300,
    },
    legs{
        .name = "AL-J-121/RC JAILBREAK",
        .type = legs_type.bipedal,
        .ap = 2000,
        .kinetic_defense = 351,
        .energy_defense = 315,
        .explosive_defense = 388,
        .attitude_stability = 658,
        .load_limit = 62600,
        .jump_distance = 132,
        .jump_height = 25,
        .weight = 18560,
        .en_load = 300,
    },
    legs{
        .name = "LG-011 MELANDER",
        .type = legs_type.bipedal,
        .ap = 4300,
        .kinetic_defense = 369,
        .energy_defense = 340,
        .explosive_defense = 361,
        .attitude_stability = 843,
        .load_limit = 60520,
        .jump_distance = 107,
        .jump_height = 28,
        .weight = 17960,
        .en_load = 365,
    },
    legs{
        .name = "LG-012 MELANDER C3",
        .type = legs_type.bipedal,
        .ap = 3980,
        .kinetic_defense = 363,
        .energy_defense = 339,
        .explosive_defense = 357,
        .attitude_stability = 835,
        .load_limit = 55440,
        .jump_distance = 138,
        .jump_height = 30,
        .weight = 16520,
        .en_load = 355,
    },
    legs{
        .name = "DF-LG-08 TIAN-QIANG",
        .type = legs_type.bipedal,
        .ap = 5300,
        .kinetic_defense = 414,
        .energy_defense = 382,
        .explosive_defense = 395,
        .attitude_stability = 925,
        .load_limit = 82600,
        .jump_distance = 90,
        .jump_height = 20,
        .weight = 26950,
        .en_load = 400,
    },
    legs{
        .name = "VP-422",
        .type = legs_type.bipedal,
        .ap = 4090,
        .kinetic_defense = 352,
        .energy_defense = 379,
        .explosive_defense = 334,
        .attitude_stability = 830,
        .load_limit = 58620,
        .jump_distance = 112,
        .jump_height = 29,
        .weight = 17170,
        .en_load = 387,
    },
    legs{
        .name = "NACHTREIHER/42E",
        .type = legs_type.bipedal,
        .ap = 3360,
        .kinetic_defense = 295,
        .energy_defense = 330,
        .explosive_defense = 298,
        .attitude_stability = 662,
        .load_limit = 48650,
        .jump_distance = 228,
        .jump_height = 52,
        .weight = 14030,
        .en_load = 462,
    },
    legs{
        .name = "VE-42A",
        .type = legs_type.bipedal,
        .ap = 5700,
        .kinetic_defense = 380,
        .energy_defense = 421,
        .explosive_defense = 387,
        .attitude_stability = 977,
        .load_limit = 85700,
        .jump_distance = 56,
        .jump_height = 14,
        .weight = 31580,
        .en_load = 465,
    },
    legs{
        .name = "2C-3000 WRECKER",
        .type = legs_type.bipedal,
        .ap = 5220,
        .kinetic_defense = 350,
        .energy_defense = 312,
        .explosive_defense = 383,
        .attitude_stability = 1003,
        .load_limit = 68900,
        .jump_distance = 86,
        .jump_height = 17,
        .weight = 23230,
        .en_load = 680,
    },
    legs{
        .name = "2S-5000 DESSERT",
        .type = legs_type.bipedal,
        .ap = 5290,
        .kinetic_defense = 382,
        .energy_defense = 392,
        .explosive_defense = 369,
        .attitude_stability = 997,
        .load_limit = 77100,
        .jump_distance = 80,
        .jump_height = 19,
        .weight = 27180,
        .en_load = 420,
    },
    legs{
        .name = "EL-TL-10 FIRMEZA",
        .type = legs_type.bipedal,
        .ap = 3600,
        .kinetic_defense = 328,
        .energy_defense = 266,
        .explosive_defense = 270,
        .attitude_stability = 737,
        .load_limit = 52100,
        .jump_distance = 155,
        .jump_height = 31,
        .weight = 11200,
        .en_load = 378,
    },
    legs{
        .name = "EL-PL-00 ALBA",
        .type = legs_type.bipedal,
        .ap = 3850,
        .kinetic_defense = 316,
        .energy_defense = 316,
        .explosive_defense = 316,
        .attitude_stability = 809,
        .load_limit = 50100,
        .jump_distance = 103,
        .jump_height = 37,
        .weight = 13150,
        .en_load = 360,
    },
    legs{
        .name = "06-041 MIND ALPHA",
        .type = legs_type.bipedal,
        .ap = 4560,
        .kinetic_defense = 370,
        .energy_defense = 390,
        .explosive_defense = 356,
        .attitude_stability = 894,
        .load_limit = 63810,
        .jump_distance = 103,
        .jump_height = 25,
        .weight = 20810,
        .en_load = 412,
    },
    legs{
        .name = "IA-C01L: EPHEMERA",
        .type = legs_type.bipedal,
        .ap = 3800,
        .kinetic_defense = 297,
        .energy_defense = 352,
        .explosive_defense = 352,
        .attitude_stability = 805,
        .load_limit = 55050,
        .jump_distance = 144,
        .jump_height = 30,
        .weight = 15200,
        .en_load = 398,
    },
    legs{
        .name = "IB-C03L: HAL 826",
        .type = legs_type.bipedal,
        .ap = 4120,
        .kinetic_defense = 359,
        .energy_defense = 380,
        .explosive_defense = 351,
        .attitude_stability = 906,
        .load_limit = 64900,
        .jump_distance = 115,
        .jump_height = 31,
        .weight = 20590,
        .en_load = 385,
    },
    legs{
        .name = "KASUAR/42Z",
        .type = legs_type.reverse_joint,
        .ap = 3580,
        .kinetic_defense = 293,
        .energy_defense = 328,
        .explosive_defense = 290,
        .attitude_stability = 686,
        .load_limit = 49280,
        .jump_distance = 386,
        .jump_height = 80,
        .weight = 16510,
        .en_load = 388,
    },
    legs{
        .name = "RC-2000 SPRING CHICKEN",
        .type = legs_type.reverse_joint,
        .ap = 4410,
        .kinetic_defense = 406,
        .energy_defense = 354,
        .explosive_defense = 380,
        .attitude_stability = 801,
        .load_limit = 70360,
        .jump_distance = 317,
        .jump_height = 70,
        .weight = 25340,
        .en_load = 402,
    },
    legs{
        .name = "06-042 MIND BETA",
        .type = legs_type.reverse_joint,
        .ap = 4020,
        .kinetic_defense = 340,
        .energy_defense = 360,
        .explosive_defense = 364,
        .attitude_stability = 788,
        .load_limit = 61600,
        .jump_distance = 334,
        .jump_height = 60,
        .weight = 19750,
        .en_load = 426,
    },
    legs{
        .name = "LG-033M VERRILL",
        .type = legs_type.tetrapod,
        .ap = 5250,
        .kinetic_defense = 402,
        .energy_defense = 357,
        .explosive_defense = 372,
        .attitude_stability = 1413,
        .load_limit = 76200,
        .jump_distance = 82,
        .jump_height = 15,
        .weight = 36200,
        .en_load = 675,
    },
    legs{
        .name = "VP-424",
        .type = legs_type.tetrapod,
        .ap = 4100,
        .kinetic_defense = 366,
        .energy_defense = 384,
        .explosive_defense = 386,
        .attitude_stability = 1366,
        .load_limit = 69800,
        .jump_distance = 103,
        .jump_height = 18,
        .weight = 31600,
        .en_load = 760,
    },
    legs{
        .name = "LAMMERGEIER/42F",
        .type = legs_type.tetrapod,
        .ap = 3560,
        .kinetic_defense = 300,
        .energy_defense = 360,
        .explosive_defense = 295,
        .attitude_stability = 980,
        .load_limit = 52460,
        .jump_distance = 53,
        .jump_height = 42,
        .weight = 22430,
        .en_load = 790,
    },
};

pub var legs_tank_soa: struct {
    name: [legs_tank_array.len][]const u8,
    type: [legs_tank_array.len]legs_type,
    ap: [legs_tank_array.len]u16,
    kinetic_defense: [legs_tank_array.len]u16,
    energy_defense: [legs_tank_array.len]u16,
    explosive_defense: [legs_tank_array.len]u16,
    attitude_stability: [legs_tank_array.len]u16,
    load_limit: [legs_tank_array.len]u32,
    travel_speed: [legs_tank_array.len]u8,
    high_speed_perf: [legs_tank_array.len]u16,
    thrust: [legs_tank_array.len]u16,
    upward_thrust: [legs_tank_array.len]u16,
    upward_en_consumption: [legs_tank_array.len]u16,
    qb_thrust: [legs_tank_array.len]u16,
    qb_jet_duration: [legs_tank_array.len]f16,
    qb_en_consumption: [legs_tank_array.len]u16,
    qb_reload_time: [legs_tank_array.len]f16,
    qb_reload_ideal_weight: [legs_tank_array.len]u32,
    ab_thrust: [legs_tank_array.len]u16,
    ab_en_consumption: [legs_tank_array.len]u16,
    weight: [legs_array.len]u16,
    en_load: [legs_array.len]u16,
} = undefined;

fn fill_legs_tank_soa() void {
    for (legs_tank_array, 0..) |e, i| {
        legs_tank_soa.name[i] = e.name;
        legs_tank_soa.type[i] = e.type;
        legs_tank_soa.ap[i] = e.ap;
        legs_tank_soa.kinetic_defense[i] = e.kinetic_defense;
        legs_tank_soa.energy_defense[i] = e.energy_defense;
        legs_tank_soa.explosive_defense[i] = e.explosive_defense;
        legs_tank_soa.attitude_stability[i] = e.attitude_stability;
        legs_tank_soa.load_limit[i] = e.load_limit;
        legs_tank_soa.travel_speed[i] = e.travel_speed;
        legs_tank_soa.high_speed_perf[i] = e.high_speed_perf;
        legs_tank_soa.thrust[i] = e.thrust;
        legs_tank_soa.qb_jet_duration[i] = e.qb_jet_duration;
        legs_tank_soa.qb_en_consumption[i] = e.qb_en_consumption;
        legs_tank_soa.qb_thrust[i] = e.qb_thrust;
        legs_tank_soa.qb_jet_duration[i] = e.qb_jet_duration;
        legs_tank_soa.qb_en_consumption[i] = e.qb_en_consumption;
        legs_tank_soa.qb_reload_time[i] = e.qb_reload_time;
        legs_tank_soa.qb_reload_ideal_weight[i] = e.qb_reload_ideal_weight;
        legs_tank_soa.ab_thrust[i] = e.ab_thrust;
        legs_tank_soa.ab_en_consumption[i] = e.ab_en_consumption;
        legs_tank_soa.weight[i] = e.weight;
        legs_tank_soa.en_load[i] = e.en_load;
    }
}

const legs_tank = struct {
    name: []const u8,
    type: legs_type,
    ap: u16,
    kinetic_defense: u16,
    energy_defense: u16,
    explosive_defense: u16,
    attitude_stability: u16,
    load_limit: u32,
    travel_speed: u8,
    high_speed_perf: u16,
    thrust: u16,
    upward_thrust: u16,
    upward_en_consumption: u16,
    qb_thrust: u16,
    qb_jet_duration: f16,
    qb_en_consumption: u16,
    qb_reload_time: f16,
    qb_reload_ideal_weight: u32,
    ab_thrust: u16,
    ab_en_consumption: u16,
    weight: u16,
    en_load: u16,
};

const legs_tank_array = [_]legs_tank{
    .{
        .name = "LG-022T BORNEMISSZA",
        .type = legs_type.tank,
        .ap = 9240,
        .kinetic_defense = 440,
        .energy_defense = 336,
        .explosive_defense = 399,
        .attitude_stability = 1500,
        .load_limit = 100300,
        .travel_speed = 150,
        .high_speed_perf = 362,
        .thrust = 4667,
        .upward_thrust = 3667,
        .upward_en_consumption = 700,
        .qb_thrust = 22150,
        .qb_jet_duration = 0.34,
        .qb_en_consumption = 810,
        .qb_reload_time = 0.8,
        .qb_reload_ideal_weight = 100300,
        .ab_thrust = 7768,
        .ab_en_consumption = 360,
        .weight = 49800,
        .en_load = 455,
    },
    .{
        .name = "VE-42B",
        .type = legs_type.tank,
        .ap = 8600,
        .kinetic_defense = 379,
        .energy_defense = 460,
        .explosive_defense = 406,
        .attitude_stability = 924,
        .load_limit = 91000,
        .travel_speed = 136,
        .high_speed_perf = 316,
        .thrust = 5984,
        .upward_thrust = 5001,
        .upward_en_consumption = 912,
        .qb_thrust = 21500,
        .qb_jet_duration = 0.4,
        .qb_en_consumption = 880,
        .qb_reload_time = 0.7,
        .qb_reload_ideal_weight = 91000,
        .ab_thrust = 10502,
        .ab_en_consumption = 430,
        .weight = 46600,
        .en_load = 824,
    },
    .{
        .name = "EL-TL-11 FORTALEZA",
        .type = legs_type.tank,
        .ap = 5100,
        .kinetic_defense = 345,
        .energy_defense = 311,
        .explosive_defense = 314,
        .attitude_stability = 822,
        .load_limit = 69300,
        .travel_speed = 194,
        .high_speed_perf = 430,
        .thrust = 5334,
        .upward_thrust = 4667,
        .upward_en_consumption = 780,
        .qb_thrust = 25000,
        .qb_jet_duration = 0.26,
        .qb_en_consumption = 720,
        .qb_reload_time = 0.5,
        .qb_reload_ideal_weight = 69300,
        .ab_thrust = 8668,
        .ab_en_consumption = 408,
        .weight = 24650,
        .en_load = 620,
    },
};

pub var booster_soa: struct {
    name: [booster_array.len][]const u8,
    thrust: [booster_array.len]u16,
    upward_thrust: [booster_array.len]u16,
    upward_en_consumption: [booster_array.len]u16,
    qb_thrust: [booster_array.len]u16,
    qb_jet_duration: [booster_array.len]f16,
    qb_en_consumption: [booster_array.len]u16,
    qb_reload_time: [booster_array.len]f16,
    qb_reload_ideal_weight: [booster_array.len]u32,
    ab_thrust: [booster_array.len]u16,
    ab_en_consumption: [booster_array.len]u16,
    melee_attack_thrust: [booster_array.len]u16,
    melee_atk_en_consump: [booster_array.len]u16,
    weight: [booster_array.len]u16,
    en_load: [booster_array.len]u16,
} = undefined;

fn fill_booster_soa() void {
    for (booster_array, 0..) |e, i| {
        booster_soa.name[i] = e.name;
        booster_soa.thrust[i] = e.thrust;
        booster_soa.upward_thrust[i] = e.upward_thrust;
        booster_soa.upward_en_consumption[i] = e.upward_en_consumption;
        booster_soa.qb_thrust[i] = e.qb_thrust;
        booster_soa.qb_jet_duration[i] = e.qb_jet_duration;
        booster_soa.qb_en_consumption[i] = e.qb_en_consumption;
        booster_soa.qb_reload_time[i] = e.qb_reload_time;
        booster_soa.qb_reload_ideal_weight[i] = e.qb_reload_ideal_weight;
        booster_soa.ab_thrust[i] = e.ab_thrust;
        booster_soa.ab_en_consumption[i] = e.ab_en_consumption;
        booster_soa.melee_attack_thrust[i] = e.melee_attack_thrust;
        booster_soa.melee_atk_en_consump[i] = e.melee_atk_en_consump;
        booster_soa.weight[i] = e.weight;
        booster_soa.en_load[i] = e.en_load;
    }
}

const booster = struct {
    name: []const u8,
    thrust: u16,
    upward_thrust: u16,
    upward_en_consumption: u16,
    qb_thrust: u16,
    qb_jet_duration: f16,
    qb_en_consumption: u16,
    qb_reload_time: f16,
    qb_reload_ideal_weight: u32,
    ab_thrust: u16,
    ab_en_consumption: u16,
    melee_attack_thrust: u16,
    melee_atk_en_consump: u16,
    weight: u16,
    en_load: u16,
};

const booster_array = [_]booster{
    .{
        .name = "AB-J-137 KIKAKU",
        .thrust = 5667,
        .upward_thrust = 4917,
        .upward_en_consumption = 656,
        .qb_thrust = 19150,
        .qb_jet_duration = 0.31,
        .qb_en_consumption = 550,
        .qb_reload_time = 0.55,
        .qb_reload_ideal_weight = 75800,
        .ab_thrust = 8218,
        .ab_en_consumption = 320,
        .melee_attack_thrust = 14019,
        .melee_atk_en_consump = 425,
        .weight = 1820,
        .en_load = 266,
    },
    .{
        .name = "BST-G1/P10",
        .thrust = 5734,
        .upward_thrust = 5084,
        .upward_en_consumption = 630,
        .qb_thrust = 17600,
        .qb_jet_duration = 0.39,
        .qb_en_consumption = 480,
        .qb_reload_time = 0.60,
        .qb_reload_ideal_weight = 65200,
        .ab_thrust = 8735,
        .ab_en_consumption = 377,
        .melee_attack_thrust = 8218,
        .melee_atk_en_consump = 529,
        .weight = 1300,
        .en_load = 130,
    },
    .{
        .name = "BST-G1/P04",
        .thrust = 6001,
        .upward_thrust = 5400,
        .upward_en_consumption = 650,
        .qb_thrust = 20600,
        .qb_jet_duration = 0.38,
        .qb_en_consumption = 560,
        .qb_reload_time = 0.56,
        .qb_reload_ideal_weight = 82000,
        .ab_thrust = 8501,
        .ab_en_consumption = 353,
        .melee_attack_thrust = 9668,
        .melee_atk_en_consump = 470,
        .weight = 1710,
        .en_load = 250,
    },
    .{
        .name = "BST-G2/P06SPD",
        .thrust = 6801,
        .upward_thrust = 5217,
        .upward_en_consumption = 672,
        .qb_thrust = 18600,
        .qb_jet_duration = 0.36,
        .qb_en_consumption = 700,
        .qb_reload_time = 0.5,
        .qb_reload_ideal_weight = 76000,
        .ab_thrust = 8685,
        .ab_en_consumption = 381,
        .melee_attack_thrust = 10652,
        .melee_atk_en_consump = 507,
        .weight = 1420,
        .en_load = 390,
    },
    .{
        .name = "ALULA/21E",
        .thrust = 6668,
        .upward_thrust = 5067,
        .upward_en_consumption = 760,
        .qb_thrust = 21650,
        .qb_jet_duration = 0.3,
        .qb_en_consumption = 690,
        .qb_reload_time = 0.35,
        .qb_reload_ideal_weight = 62400,
        .ab_thrust = 9035,
        .ab_en_consumption = 435,
        .melee_attack_thrust = 10868,
        .melee_atk_en_consump = 575,
        .weight = 1900,
        .en_load = 410,
    },
    .{
        .name = "FLUEGEL/21Z",
        .thrust = 6251,
        .upward_thrust = 5634,
        .upward_en_consumption = 680,
        .qb_thrust = 20000,
        .qb_jet_duration = 0.4,
        .qb_en_consumption = 600,
        .qb_reload_time = 0.5,
        .qb_reload_ideal_weight = 73800,
        .ab_thrust = 8668,
        .ab_en_consumption = 398,
        .melee_attack_thrust = 12335,
        .melee_atk_en_consump = 485,
        .weight = 1980,
        .en_load = 282,
    },
    .{
        .name = "BUERZEL/21D",
        .thrust = 6167,
        .upward_thrust = 4834,
        .upward_en_consumption = 710,
        .qb_thrust = 18050,
        .qb_jet_duration = 0.26,
        .qb_en_consumption = 676,
        .qb_reload_time = 0.91,
        .qb_reload_ideal_weight = 100600,
        .ab_thrust = 9301,
        .ab_en_consumption = 378,
        .melee_attack_thrust = 10402,
        .melee_atk_en_consump = 588,
        .weight = 2240,
        .en_load = 480,
    },

    .{
        .name = "BC-0600 12345",
        .thrust = 5801,
        .upward_thrust = 5200,
        .upward_en_consumption = 800,
        .qb_thrust = 18900,
        .qb_jet_duration = 0.54,
        .qb_en_consumption = 520,
        .qb_reload_time = 0.80,
        .qb_reload_ideal_weight = 97000,
        .ab_thrust = 8084,
        .ab_en_consumption = 372,
        .melee_attack_thrust = 8118,
        .melee_atk_en_consump = 496,
        .weight = 1360,
        .en_load = 180,
    },

    .{
        .name = "BC-0400 MULE",
        .thrust = 5417,
        .upward_thrust = 4767,
        .upward_en_consumption = 405,
        .qb_thrust = 17500,
        .qb_jet_duration = 0.46,
        .qb_en_consumption = 670,
        .qb_reload_time = 0.58,
        .qb_reload_ideal_weight = 80000,
        .ab_thrust = 7584,
        .ab_en_consumption = 381,
        .melee_attack_thrust = 7018,
        .melee_atk_en_consump = 390,
        .weight = 970,
        .en_load = 200,
    },

    .{
        .name = "BC-0200 GRIDWALKER",
        .thrust = 6401,
        .upward_thrust = 6334,
        .upward_en_consumption = 660,
        .qb_thrust = 19000,
        .qb_jet_duration = 0.33,
        .qb_en_consumption = 660,
        .qb_reload_time = 0.7,
        .qb_reload_ideal_weight = 60900,
        .ab_thrust = 8585,
        .ab_en_consumption = 387,
        .melee_attack_thrust = 11468,
        .melee_atk_en_consump = 520,
        .weight = 2010,
        .en_load = 244,
    },

    .{
        .name = "IA-C01B: GILLS",
        .thrust = 6534,
        .upward_thrust = 5334,
        .upward_en_consumption = 580,
        .qb_thrust = 18850,
        .qb_jet_duration = 0.28,
        .qb_en_consumption = 620,
        .qb_reload_time = 0.3,
        .qb_reload_ideal_weight = 68300,
        .ab_thrust = 8335,
        .ab_en_consumption = 391,
        .melee_attack_thrust = 6184,
        .melee_atk_en_consump = 630,
        .weight = 1590,
        .en_load = 400,
    },

    .{
        .name = "IB-C03B: NGI 001",
        .thrust = 6467,
        .upward_thrust = 6001,
        .upward_en_consumption = 750,
        .qb_thrust = 22200,
        .qb_jet_duration = 0.43,
        .qb_en_consumption = 740,
        .qb_reload_time = 0.63,
        .qb_reload_ideal_weight = 90200,
        .ab_thrust = 8835,
        .ab_en_consumption = 405,
        .melee_attack_thrust = 10535,
        .melee_atk_en_consump = 558,
        .weight = 1930,
        .en_load = 342,
    },
};

pub var fcs_soa: struct {
    name: [fcs_array.len][]const u8,
    close_range_assist: [fcs_array.len]u8,
    medium_range_assist: [fcs_array.len]u8,
    long_range_assist: [fcs_array.len]u8,
    missile_lock_correction: [fcs_array.len]u8,
    multi_lock_correction: [fcs_array.len]u8,
    weight: [fcs_array.len]u16,
    en_load: [fcs_array.len]u16,
} = undefined;

fn fill_fcs_soa() void {
    for (fcs_array, 0..) |e, i| {
        fcs_soa.name[i] = e.name;
        fcs_soa.close_range_assist[i] = e.close_range_assist;
        fcs_soa.medium_range_assist[i] = e.medium_range_assist;
        fcs_soa.long_range_assist[i] = e.long_range_assist;
        fcs_soa.missile_lock_correction[i] = e.missile_lock_correction;
        fcs_soa.multi_lock_correction[i] = e.multi_lock_correction;
        fcs_soa.weight[i] = e.weight;
        fcs_soa.en_load[i] = e.en_load;
    }
}

const fcs = struct {
    name: []const u8,
    close_range_assist: u8,
    medium_range_assist: u8,
    long_range_assist: u8,
    missile_lock_correction: u8,
    multi_lock_correction: u8,
    weight: u16,
    en_load: u16,
};

const fcs_array = [_]fcs{
    .{
        .name = "FCS-G1/P01",
        .close_range_assist = 38,
        .medium_range_assist = 27,
        .long_range_assist = 20,
        .missile_lock_correction = 79,
        .multi_lock_correction = 40,
        .weight = 80,
        .en_load = 198,
    },
    .{
        .name = "FCS-G2/P05",
        .close_range_assist = 42,
        .medium_range_assist = 80,
        .long_range_assist = 26,
        .missile_lock_correction = 105,
        .multi_lock_correction = 60,
        .weight = 100,
        .en_load = 232,
    },
    .{
        .name = "FCS-G2/P10SLT",
        .close_range_assist = 31,
        .medium_range_assist = 41,
        .long_range_assist = 29,
        .missile_lock_correction = 128,
        .multi_lock_correction = 90,
        .weight = 120,
        .en_load = 209,
    },
    .{
        .name = "FCS-G2/P12SML",
        .close_range_assist = 28,
        .medium_range_assist = 52,
        .long_range_assist = 30,
        .missile_lock_correction = 118,
        .multi_lock_correction = 120,
        .weight = 130,
        .en_load = 278,
    },
    .{
        .name = "FC-006 ABBOT",
        .close_range_assist = 70,
        .medium_range_assist = 32,
        .long_range_assist = 5,
        .missile_lock_correction = 74,
        .multi_lock_correction = 46,
        .weight = 90,
        .en_load = 266,
    },
    .{
        .name = "FC-008 TALBOT",
        .close_range_assist = 63,
        .medium_range_assist = 54,
        .long_range_assist = 11,
        .missile_lock_correction = 103,
        .multi_lock_correction = 62,
        .weight = 140,
        .en_load = 312,
    },
    .{
        .name = "VE-21A",
        .close_range_assist = 36,
        .medium_range_assist = 67,
        .long_range_assist = 92,
        .missile_lock_correction = 65,
        .multi_lock_correction = 79,
        .weight = 85,
        .en_load = 364,
    },
    .{
        .name = "VE-21B",
        .close_range_assist = 15,
        .medium_range_assist = 76,
        .long_range_assist = 80,
        .missile_lock_correction = 97,
        .multi_lock_correction = 70,
        .weight = 160,
        .en_load = 388,
    },
    .{
        .name = "IA-C01F: OCELLUS",
        .close_range_assist = 90,
        .medium_range_assist = 12,
        .long_range_assist = 3,
        .missile_lock_correction = 85,
        .multi_lock_correction = 50,
        .weight = 130,
        .en_load = 292,
    },
    .{
        .name = "IB-C03F: WLT 001",
        .close_range_assist = 58,
        .medium_range_assist = 77,
        .long_range_assist = 54,
        .missile_lock_correction = 102,
        .multi_lock_correction = 66,
        .weight = 150,
        .en_load = 486,
    },
};

pub var generator_soa: struct {
    name: [generator_array.len][]const u8,
    en_capacity: [generator_array.len]u16,
    en_recharge: [generator_array.len]u16,
    supply_recovery: [generator_array.len]u16,
    post_recovery_en_supply: [generator_array.len]u16,
    energy_firearm_spec: [generator_array.len]u8,
    weight: [generator_array.len]u16,
    en_output: [generator_array.len]u16,
} = undefined;

fn fill_generator_soa() void {
    for (generator_array, 0..) |e, i| {
        generator_soa.name[i] = e.name;
        generator_soa.en_capacity[i] = e.en_capacity;
        generator_soa.en_recharge[i] = e.en_recharge;
        generator_soa.supply_recovery[i] = e.supply_recovery;
        generator_soa.post_recovery_en_supply[i] = e.post_recovery_en_supply;
        generator_soa.energy_firearm_spec[i] = e.energy_firearm_spec;
        generator_soa.weight[i] = e.weight;
        generator_soa.en_output[i] = e.en_output;
    }
}

const generator = struct {
    name: []const u8,
    en_capacity: u16,
    en_recharge: u16,
    supply_recovery: u16,
    post_recovery_en_supply: u16,
    energy_firearm_spec: u8,
    weight: u16,
    en_output: u16,
};

pub const generator_array = [_]generator{
    .{
        .name = "AG-J-098 JOSO",
        .en_capacity = 2300,
        .en_recharge = 769,
        .supply_recovery = 500,
        .post_recovery_en_supply = 400,
        .energy_firearm_spec = 72,
        .weight = 3420,
        .en_output = 2600,
    },
    .{
        .name = "AG-E-013 YABA",
        .en_capacity = 2850,
        .en_recharge = 1000,
        .supply_recovery = 555,
        .post_recovery_en_supply = 1000,
        .energy_firearm_spec = 95,
        .weight = 5080,
        .en_output = 3000,
    },
    .{
        .name = "AG-T-005 HOKUSHI",
        .en_capacity = 3160,
        .en_recharge = 952,
        .supply_recovery = 370,
        .post_recovery_en_supply = 850,
        .energy_firearm_spec = 90,
        .weight = 7080,
        .en_output = 3810,
    },
    .{
        .name = "DF-GN-02 LING-TAI",
        .en_capacity = 2000,
        .en_recharge = 2000,
        .supply_recovery = 833,
        .post_recovery_en_supply = 280,
        .energy_firearm_spec = 61,
        .weight = 3860,
        .en_output = 2340,
    },
    .{
        .name = "DF-GN-06 MING-TANG",
        .en_capacity = 2900,
        .en_recharge = 1250,
        .supply_recovery = 666,
        .post_recovery_en_supply = 440,
        .energy_firearm_spec = 76,
        .weight = 6320,
        .en_output = 3160,
    },
    .{
        .name = "DF-GN-08 SAN-TAI",
        .en_capacity = 4420,
        .en_recharge = 1176,
        .supply_recovery = 625,
        .post_recovery_en_supply = 810,
        .energy_firearm_spec = 88,
        .weight = 10060,
        .en_output = 3210,
    },
    .{
        .name = "VP-20S",
        .en_capacity = 2500,
        .en_recharge = 833,
        .supply_recovery = 434,
        .post_recovery_en_supply = 1200,
        .energy_firearm_spec = 94,
        .weight = 3800,
        .en_output = 3200,
    },
    .{
        .name = "VP-20C",
        .en_capacity = 2720,
        .en_recharge = 909,
        .supply_recovery = 454,
        .post_recovery_en_supply = 1100,
        .energy_firearm_spec = 100,
        .weight = 5320,
        .en_output = 3670,
    },
    .{
        .name = "VP-20D",
        .en_capacity = 3590,
        .en_recharge = 714,
        .supply_recovery = 384,
        .post_recovery_en_supply = 1400,
        .energy_firearm_spec = 104,
        .weight = 11030,
        .en_output = 4430,
    },
    .{
        .name = "VE-20A",
        .en_capacity = 2460,
        .en_recharge = 740,
        .supply_recovery = 416,
        .post_recovery_en_supply = 600,
        .energy_firearm_spec = 116,
        .weight = 3590,
        .en_output = 3120,
    },
    .{
        .name = "VE-20B",
        .en_capacity = 3300,
        .en_recharge = 763,
        .supply_recovery = 392,
        .post_recovery_en_supply = 800,
        .energy_firearm_spec = 150,
        .weight = 5860,
        .en_output = 2890,
    },
    .{
        .name = "vE-20C",
        .en_capacity = 3690,
        .en_recharge = 555,
        .supply_recovery = 377,
        .post_recovery_en_supply = 720,
        .energy_firearm_spec = 128,
        .weight = 10130,
        .en_output = 4090,
    },
    .{
        .name = "IA-CO1G: AORTA",
        .en_capacity = 3000,
        .en_recharge = 238,
        .supply_recovery = 333,
        .post_recovery_en_supply = 2000,
        .energy_firearm_spec = 105,
        .weight = 4330,
        .en_output = 3500,
    },
    .{
        .name = "IB-C03G: NGI 000",
        .en_capacity = 4400,
        .en_recharge = 250,
        .supply_recovery = 312,
        .post_recovery_en_supply = 3300,
        .energy_firearm_spec = 110,
        .weight = 8950,
        .en_output = 4340,
    },
};
